//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SayHi {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Answers {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Answers() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SayHi.Answers", typeof(Answers).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am fine. Thank you, you too?.
        /// </summary>
        internal static string H1 {
            get {
                return ResourceManager.GetString("H1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string H10 {
            get {
                return ResourceManager.GetString("H10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am good. How&apos;s about you?.
        /// </summary>
        internal static string H2 {
            get {
                return ResourceManager.GetString("H2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am great. How is going today?.
        /// </summary>
        internal static string H3 {
            get {
                return ResourceManager.GetString("H3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am five years old..
        /// </summary>
        internal static string H4 {
            get {
                return ResourceManager.GetString("H4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My name Alexa.
        /// </summary>
        internal static string H5 {
            get {
                return ResourceManager.GetString("H5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string H6 {
            get {
                return ResourceManager.GetString("H6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string H7 {
            get {
                return ResourceManager.GetString("H7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string H8 {
            get {
                return ResourceManager.GetString("H8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string H9 {
            get {
                return ResourceManager.GetString("H9", resourceCulture);
            }
        }
    }
}
